#!/usr/bin/env bash

echo "------------- installing aerospace -------------"
os_name="$(uname)"

if [[ "$os_name" == "Darwin" ]]; then
  echo "Running macOS-specific code..."
  brew install --cask nikitabobko/tap/aerospace
elif [[ "$os_name" == "Linux" ]]; then
  echo "Running Linux-specific code..."
else
  echo "Unsupported operating system: $os_name"
  exit 1
fi
