#!/usr/bin/env bash

if ! command -v fish >/dev/null 2>&1; then
  echo "Installing fish..."
  brew install fish
else
  echo "fish is already installed."
fi

if ! grep -Fxq "/opt/homebrew/bin/fish" /etc/shells; then
  echo "Adding fish to /etc/shells..."
  echo /opt/homebrew/bin/fish | sudo tee -a /etc/shells
else
  echo "fish is already listed in /etc/shells."
fi

if [ "$SHELL" != "/opt/homebrew/bin/fish" ]; then
  echo "Changing shell to fish..."
  chsh -s /opt/homebrew/bin/fish
else
  echo "fish is already the default shell."
fi

if ! fish -c "fisher --version" >/dev/null 2>&1; then
  echo "Installing fisher..."
  # https://raw.githubusercontent.com/jorgebucaran/fisher/HEAD/functions/fisher.fish
  # Make sure to always review `curl installs` before blindly running it.
  fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source; fisher install jorgebucaran/fisher"
else
  echo "fisher is already installed."
fi

fish -c "fisher install PatrickF1/fzf.fish"
fish -c "fisher install catppuccin/fish"
fish -c "fisher install jorgebucaran/nvm.fish"

fish -c "fish_add_path /opt/homebrew/bin"
fish -c "fish_add_path $HOME/.local/bin"
fish -c "set --universal nvm_default_version v22.14.0"
