#!/usr/bin/env bash

echo "------------- installing jankyborders -------------"
os_name="$(uname)"

if [[ "$os_name" == "Darwin" ]]; then
  echo "Running macOS-specific code..."
  brew tap FelixKratz/formulae
  brew install borders
elif [[ "$os_name" == "Linux" ]]; then
  echo "Running Linux-specific code..."
else
  echo "Unsupported operating system: $os_name"
  exit 1
fi
