#!/usr/bin/env bash

git clone -b v0.10.4 https://github.com/neovim/neovim.git $HOME/projects/personal/neovim

echo "------------- installing neovim -------------"
os_name="$(uname)"

if [[ "$os_name" == "Darwin" ]]; then
  echo "Running macOS-specific code..."
  brew install ninja cmake gettext curl
elif [[ "$os_name" == "Linux" ]]; then
  echo "Running Linux-specific code..."
else
  echo "Unsupported operating system: $os_name"
  exit 1
fi

cd $HOME/projects/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
