#!/usr/bin/env bash

git clone -b tmux-3-5a https://github.com/tmux/tmux.git $HOME/projects/persoanl/tmux

echo "------------- installing neovim -------------"
os_name="$(uname)"

if [[ "$os_name" == "Darwin" ]]; then
  echo "Running macOS-specific code..."
  brew install autoconf automake pkg-config
elif [[ "$os_name" == "Linux" ]]; then
  echo "Running Linux-specific code..."
  sudo apt -y install autoconf automake pkg-config
else
  echo "Unsupported operating system: $os_name"
  exit 1
fi

cd $HOME/projects/personal/tmux
sh autogen.sh
./configure && make
