return {
  -- {
  --   "hrsh7th/nvim-cmp",
  --   dependencies = {
  --     "Jezda1337/nvim-html-css",
  --   },
  --   opts = {
  --     sources = {
  --       {
  --         name = "html-css",
  --         option = {
  --           enable_on = { "html" },
  --           notify = false,
  --           documentation = {
  --             auto_show = true,
  --           },
  --           style_sheets = {
  --             "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
  -- {
  --   "saghen/blink.cmp",
  --   opts = {
  --     sources = {
  --       compat = { "html-css" },
  --     },
  --   },
  -- },
}
